# Generated by Django 4.2.13 on 2024-06-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bookinge',
            new_name='Booking',
        ),
    ]
