# Generated by Django 4.2.13 on 2024-06-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_bookinge_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
