# Generated by Django 4.2.13 on 2024-06-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_no_of_guests_alter_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
