# Generated by Django 4.2.16 on 2024-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataShieldMDApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithmparameter',
            name='t_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
